; Script to boot ElfOS on the SCB1802 emulator.
;  Note that you can boot from either IDE or TU58!
SET LOGGING/CONSOLE/LEVEL=WARNING
SET CPU/EXTENDED
ATTACH DISK ElfOSv5.dsk/UNIT=0
ATTACH DISK empty.dsk/UNIT=1/CAPACITY=16536
ATTACH TAPE ElfOSv5.tu58/UNIT=0
SET DEVICE SLU1/TXSPEED=400
CLEAR MEMORY
LOAD eprom.hex/ROM
;LOAD/RAM/BASE=FE00 nvr.bin
RUN
SAVE/RAM/BASE=FE00/COUNT=224/FORMAT=BINARY/OVERWRITE nvr.bin
