; ELF2K Emulator script to run the basic Spare Time Gizmos EPROM ...
SET MEMORY/RAM 0-7FFF
SET MEMORY/ROM 8000-0FFFF
SHOW MEMORY
ATTACH TIL311
ATTACH SWITCHES
ATTACH SERIAL EF3
SET SERIAL /BAUD=1200 /NOINVERT=TX
SET CPU/EFDEFAULT=1,1,1,0/NOEXTENDED
LOAD Elf2K-alternate-v120/ROM
SHOW CONFIGURATION
SET LOG/CONSOLE/LEVEL=WARNING
RUN 8000
